databases:
  presto:
    jdbc_url: "jdbc:presto://${databases.presto.host}:${databases.presto.port}/hive/${databases.hive.schema};\
      SSL=1;\
      SSLTrustStorePath=${databases.presto.https_keystore_path};\
      SSLTrustStorePwd=${databases.presto.https_keystore_password};\
      AuthenticationType=Kerberos Authentication;\
      DisableKerberosReverseDNS=1;\
      KrbServiceName=${databases.presto.cli_kerberos_service_name}"

command:
  suite:
    - kinit -kt ${databases.presto.cli_kerberos_keytab} ${databases.presto.cli_kerberos_principal}
