databases:
  hive:
    host: hadoop-master
  presto:
    host: presto-master
    configured_hdfs_user: hive
    jdbc_driver_class: com.teradata.presto.jdbc42.Driver
    jdbc_url: jdbc:presto://${databases.presto.server_address}/hive/${databases.hive.schema};TimeZoneID=Africa/Abidjan;
    cli_ldap_truststore_path: /etc/openldap/certs/cacerts.jks
    cli_ldap_truststore_password: testldap
    cli_ldap_user_name: DefaultGroupUser
    cli_ldap_user_password: LDAPPass123
    cli_ldap_server_address: https://${databases.presto.host}:8443
